'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class RecipeBook

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents pnlSearch As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents lnkAll As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents rptCategories As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents lblResultCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents rptRecipes As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents lblNoResults As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents pnlRecipe As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents lnkBack As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litRecipeName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litCategory As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents pnlPrep As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litPrepTime As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents pnlCook As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litCookTime As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents pnlRest As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litRestTime As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents pnlServings As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litServings As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents pnlSource As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litSource As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litIngredients As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litDirections As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents pnlNotes As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litNotes As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents pnlNutrition As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litCalories As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litFat As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litSatFat As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litCholesterol As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litSodium As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litCarbs As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litFiber As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litSugar As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litProtein As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''{cid} control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''</remarks>
    Protected WithEvents litServingNote As Global.System.Web.UI.WebControls.Literal

End Class
